# Generated by Django 5.0 on 2024-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='portion_calories',
            field=models.FloatField(default=10, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
