# Generated by Django 5.0.6 on 2024-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_usermeal_portion_carbohydrates_usermeal_portion_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(),
        ),
    ]
