# Generated by Django 5.0 on 2024-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_fooditem_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], default='breakfast', max_length=20),
            preserve_default=False,
        ),
    ]
